version: "2"
services:
  alarmservice_test:
    image: com.infinera.metro.service.alarm.acceptance/alarmservice-acceptance-test:1.0-SNAPSHOT
    container_name: alarmservice_test
    networks:
      alarmservice_network:
    depends_on:
      - alarmservice
      - nodes_setup
    links:
        - alarmservice
    entrypoint: ./wait-for-it.sh
    command: alarmservice:8080 --timeout=30 --strict -- ./entrypoint.sh